hotel/urls.py
from django.urls import path, include
from .views import RoomListView, RoomCreateView, RoomDeleteView, RoomDetailView, RoomUpdateView
from reservation.views import AvailableRoomsListView, SearchRoomListView
urlpatterns = [
    path("search/", SearchRoomListView.as_view(), name="room_search"),
    path('all/', RoomListView.as_view(), name='room_list'),
    path('available/', AvailableRoomsListView.as_view(), name='room_available'),
    path('add/', RoomCreateView.as_view(), name='room_create'),
    path('<slug>/booking/', include('reservation.urls')),
    path('<slug>/', RoomDetailView.as_view(), name='room_detail'),
    path('<slug>/delete/', RoomDeleteView.as_view(), name='room_delete'),
    path('<slug>/edit/', RoomUpdateView.as_view(), name='room_update'),
]

hotelsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('rooms/', include('hotel.urls')),
    path('bookings/', include('reservation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
import uuid
from django.utils.text import slugify
from django.utils import timezone
import re
from pathlib import Path
from datetime import date
from number_generator import generate_number
from django.db.models.signals import post_save, pre_save

def generateRoomNumber():
    rooms = Room.objects.all().order_by('-created_at')
    return generate_number('R', rooms, length=10)

# Create your models here.

class RoomExtra(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    roomextra_name = models.CharField(_("Name of Extra"), max_length=50)
    roomextra_cost = models.DecimalField(_("Cost"), max_digits=5, decimal_places=2)
    roomextra_info1 = models.CharField(_("Room Extra Info"), max_length=50, blank=True, null=True)
    roomextra_info2 = models.CharField(_("Room Extra Info 2"), max_length=50, blank=True, null=True)
    roomextra_date1 = models.DateTimeField(_("Room Extra Date 1"), auto_now=False, auto_now_add=False, blank=True, null=True)
    roomextra_date2 = models.DateTimeField(_("Room Extra Date 2"), auto_now=False, auto_now_add=False, blank=True, null=True)
    roomextra_active = models.BooleanField(_("Is Active?"), default=True)
    

    class Meta:
        verbose_name = _("RoomExtra")
        verbose_name_plural = _("RoomExtras")

    def __str__(self):
        return self.roomextra_name

    def get_absolute_url(self):
        return reverse("RoomExtra_detail", kwargs={"pk": self.pk})


class RoomType(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    roomtype_name = models.CharField(_("Name"), max_length=50)
    roomtype_cost = models.DecimalField(_("Cost of Room/Night"), max_digits=5, decimal_places=2)
    roomtype_cost1 = models.DecimalField(_("Cost of Room/Night 1"), max_digits=5, decimal_places=2, blank=True, null=True)
    roomtype_info = models.CharField(_("RoomType Info 1"), max_length=50, blank=True, null=True)
    roomtype_active = models.BooleanField(_("Is Active?"), default=True)


    class Meta:
        verbose_name = _("RoomType")
        verbose_name_plural = _("RoomTypes")

    def __str__(self):
        return self.roomtype_name

    def get_absolute_url(self):
        return reverse("RoomType_detail", kwargs={"pk": self.pk})

ROOMSTATUS = [
    ('cv', 'Clean Vacant'),
    ('co', 'Clean Occupied'),
    ('dv', 'Dirty Vacant'),
    ('do', 'Dirty Occupied'),
]


class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    roomstatus = models.CharField(_("Room Status"), max_length=2, choices=ROOMSTATUS, default='dv')
    roomnumber = models.CharField(_("Room Number"), max_length=50, default=generateRoomNumber, db_index=True, unique=True)
    roomnumber_url = models.SlugField(_("Room Number URL"), null=True)
    #limit_choices_to limits the availabe choices for this field/Will show only roomtypes with roomtype_active = True
    roomtype = models.ForeignKey(RoomType, on_delete=models.CASCADE, limit_choices_to={'roomtype_active': True}, related_name='rooms') 
    roomcapacity = models.PositiveIntegerField(_("Room Capacity")) #todo: set max value for room capacity
    roombed = models.PositiveIntegerField(_("Number of Beds"))
    roombath = models.PositiveIntegerField(_("Number of Bath"))
    roomdimension = models.DecimalField(_("Dimension (in Square Feet)"), max_digits=5, decimal_places=2)
    roomextras = models.ManyToManyField(RoomExtra, verbose_name=_("List of Extra Items"))
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    last_updated = models.DateTimeField(_("Updated At"), auto_now=True)
    is_available = models.BooleanField(_("Room Available"), default=True)
    roomdate = models.DateTimeField(_("Empty Date Field"), blank=True, null=True)

    # TODO: add a model manager to handle getting rooms according to status
    
    
    class Meta:
        verbose_name = _("Room")
        verbose_name_plural = _("Rooms")

    def __str__(self):
        return self.roomnumber

    def get_absolute_url(self):
        return reverse("room_detail", kwargs={"slug": self.roomnumber_url})

def room_pre_save(sender, instance, *args, **kwargs):
    if instance.roomnumber_url is None:
        instance.roomnumber_url = slugify(instance.roomnumber)

pre_save.connect(room_pre_save, sender=Room)

def room_image_upload_handler(instance, filename):
    fpath = Path(filename)
    newfilename = str(uuid.uuid4())
    return f'photos/rooms/{date.today().year}/{date.today().month}/{date.today().day}/{newfilename}{fpath.suffix}'


class RoomImage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room = models.ForeignKey(Room, verbose_name=_("Room"), on_delete=models.CASCADE, related_name='images')
    roomimage_main = models.ImageField(_("Main Room Image"), upload_to=room_image_upload_handler, max_length=None)
    roomimage_1 = models.ImageField(_("Room Image 1"), upload_to=room_image_upload_handler, max_length=None, blank=True, null=True)
    roomimage_2 = models.ImageField(_("Room Image 2"), upload_to=room_image_upload_handler, max_length=None, blank=True, null=True)
    roomimage_3 = models.ImageField(_("Room Image 3"), upload_to=room_image_upload_handler, max_length=None, blank=True, null=True)
    roomimage_4 = models.ImageField(_("Room Image 4"), upload_to=room_image_upload_handler, max_length=None, blank=True, null=True)
    roomimage_5 = models.ImageField(_("Room Image 5"), upload_to=room_image_upload_handler, max_length=None, blank=True, null=True)
    

    class Meta:
        verbose_name = _("RoomImage")
        verbose_name_plural = _("RoomImages")

    def __str__(self):
        return self.room.roomnumber

    def get_absolute_url(self):
        return reverse("RoomImage_detail", kwargs={"pk": self.pk})

templates/rooms/homelist.html
{% extends 'base.html' %}
{% block title %}
Rooms Page
{% endblock title %}



{% block content %}
    <!-- list of rooms -->
    <div class="row">
        {% for room in rooms %}
            <div class="col-sm-6">
                <div class="card">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ room.roomnumber }}</h5>
                        <p class="card-text">
                            <ul class="extras">
                                {% for extra in room.roomextras_set.all %}
                                    <li class="extraitem">{{ extra.roomextra_name }}</li>
                                {% endfor %}
                            </ul>
                        </p>
                        <a href="{% url 'room_detail' room.roomnumber_url %}" class="btn btn-dark">View Room</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="create-room">
        <a href="{% url 'room_create' %}"><button class="btn btn-primary">Create Room</button></a>
    </div>
    
{% endblock content %}

templates/rooms/room_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="delete-header">Are you sure you want to delete this room?</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes, I'm Sure">
</form>
<a href="{% url 'room_detail' room.roomnumber_url %}"><button class="btn btn-primary">No, Take Me Back</button></a>

{% endblock content %}

templates/rooms/roomcreate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-dark" type="submit" value="Submit">
        <a href="{% url 'room_list' %}">Cancel</a>
    </form>
{% endblock content %}

templates/rooms/roomdetail.html
{% extends 'base.html' %}

{% block content %}
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="..." class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="..." class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="..." class="d-block w-100" alt="...">
        </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="room-items">
        <table class="table table-striped">
            <!-- <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
              </tr>
            </thead> -->

            <!-- todo: reduce width of table and position it to the center [CSS] -->
            <tbody>
              <tr>
                <th scope="row">Room Number</th>
                <td>{{ room.roomnumber }}</td>
                <th scope="row">Room Type</th>
                <td>{{ room.roomtype }}</td>
              </tr>
              <tr>
                <th scope="row">Room Status</th>
                <td>{{ room.get_roomstatus_display }}</td>
                <th scope="row"><i><small>something here</small></i></th>
                <td>
                    <ul>
                        {% for roomextra  in room.roomextras_set.all %}
                            <li>
                                {{ roomextra }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
              </tr>
              <tr>
                <th scope="row">Room Dimension</th>
                <td>{{ room.roomdimension }}</td>
                <th scope="row">Room Capacity</th>
                <td>{{ room.roomcapacity }}</td>
              </tr>
              <tr>
                <th scope="row">Number of Beds</th>
                <td>{{ room.roombed }}</td>
                <th scope="row">Number of Baths</th>
                <td>{{ room.roombath }}</td>
              </tr>
            </tbody>
        </table>
    </div>
    <div class="room-list">
        <a href="{% url 'room_list' %}"><button class="btn btn-primary">View All Rooms</button></a>
        <a href="{% url 'room_delete' room.roomnumber_url %}"><button class="btn btn-danger">Delete Room</button></a>
        <a href="{% url 'booking_create' room.roomnumber_url %}"><button class="btn btn-dark">Book This Room</button></a>
    </div>
    {% if bookings is not None %}
      <div class="bookingstable">
        <div class="bookingtitle">
          <h1>Booking Details</h1>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Booking Number</th>
              <th>Client</th>
              <th>Booked From</th>
              <th>Booked To</th>
              <th>Booking Confirmed</th>
            </tr>
          </thead>
          <tbody>
            {% for booking in bookings %}
              <tr>
                <td>{{ booking.bookingnumber }}</td>
                <td>{{ booking.bookingby }}</td>
                <td>{{ booking.bookingfrom }}</td>
                <td>{{ booking.bookingto }}</td>
                <td>{{ booking.bookingconfirm }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
    {% comment %} room.roomnumber_url  {% endcomment %}
{% endblock content %}

templates/rooms/roomsearch.html
{% extends 'base.html' %}

{% block content %}
    <form method="get">
        <div>
            <label for="fromdate">Booking From</label>
            <input type="date" name="fromdate" id="fromdate">
        </div>
        <div>
            <label for="todate">Booking From</label>
            <input type="date" name="todate" id="todate">
        </div>
        <input class="btn btn-primary" type="submit" value="Search">
    </form>
{% endblock content %}

templates/rooms/roomupdate.html
{% extends 'extras/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark">Update Room Details</button>
    </form>
{% endblock content %}